require("plugins.components.lualine")
require("plugins.components.tree")
require("plugins.components.telescope")
require("plugins.components.treesitter-context")
require("plugins.components.aerial")
require("plugins.components.bufferline")
require("plugins.components.toggleterm")
